
---
language: node_js
node_js:
  - 'node'
sudo: false
before_install:
  - npm i -g npm@latest
install:
  - npm ci
  - npm install -g babel-eslint
before_script:
  - make lint
script:
  - make test-all
